### ISSUE TITLE
checklist

### ISSUE THREAD

**Issue by cshen6** [neurodata/Multiscale-Network-Test#8]
This list is for checking by myself:
- [x] Check theorem and corollary and proofs
- [x] Are we still doing Node contributions?
- [ ] Consider another corollary for weighted & directed graph

After Monday:
- [x] exclude 3.4? due to growing variance.
- [ ] add a real data where MGC is best?
- [x] should we add multivariate node attribute?
- [x] check figure 5 for 11
- [x] check proof of thm 2.5
- [x] check node contribution for SBM model

**Comment by jovo** [comment]
#### notes to discuss:
- [x] remove Ctilde row from fig 4
- [x] improve fig 5: make the scale the same for left and right pane, for the y-axis. Also add the critical value (the redline) to the x-axis, and add the actual power (the area under blue curve to the right of the redline) underneath the curve.
- [x] improve fig 10: what happens after theta=0.5? And is this a universal pattern, i.e., whether change 0.5 to something else, and 0.2 to something else, always exhibit the same power pattern for theta?
- [x] discuss fig 13: to be discussed
- [ ] try a multivariate simulation (2D gaussian mixture)?
